export const GET_ALL_POLICY_REQUEST = "NEW_POLICY_REQUEST";
export const GET_ALL_POLICY_SUCCESS = "NEW_POLICY_SUCCESS";
export const GET_ALL_POLICY_FAIL = "NEW_POLICY_FAIL";
export const GET_ALL_POLICY_RESET = "GET_ALL_POLICY_RESET";

export const UPDATE_POLICY_REQUEST = "UPDATE_POLICY_REQUEST";
export const UPDATE_POLICY_SUCCESS = "UPDATE_POLICY_SUCCESS";
export const UPDATE_POLICY_FAIL = "UPDATE_POLICY_FAIL";
export const UPDATE_POLICY_RESET = "UPDATE_POLICY_RESET";

export const GET_ALL_INSURANCE_FIRM_REQUEST = "GET_ALL_INSURANCE_FIRM_REQUEST";
export const GET_ALL_INSURANCE_FIRM_SUCCESS = "GET_ALL_INSURANCE_FIRM_SUCCESS";
export const GET_ALL_INSURANCE_FIRM_FAIL = "GET_ALL_INSURANCE_FIRM_FAIL";
export const GET_ALL_INSURANCE_FIRM_RESET = "GET_ALL_INSURANCE_FIRM_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";