export const GET_ALL_CLAIMS_REQUEST = "GET_ALL_CLAIMS_REQUEST";
export const GET_ALL_CLAIMS_SUCCESS = "GET_ALL_CLAIMS_SUCCESS";
export const GET_ALL_CLAIMS_FAIL = "GET_ALL_CLAIMS_FAIL";
export const GET_ALL_CLAIMS_RESET = "GET_ALL_CLAIMS_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_IPFS_HASH_REQUEST = "GET_IPFS_HASH_REQUEST"
export const GET_IPFS_HASH_SUCCESS = "GET_IPFS_HASH_SUCCESS"
export const GET_IPFS_HASH_FAIL = "GET_IPFS_HASH_FAIL"
export const GET_IPFS_HASH_RESET = "GET_IPFS_HASH_RESET"
